channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==24.2
  - psutil==7.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.16.0
name: mlflow-env
