# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL 16
    type: postgres
    access: proxy
    url: db:5432
    database: test_monitor
    user: postgres
    secureJsonData:
      password: ""
    jsonData:
      sslmode: "disable"
      database: test_monitor
